# Homework Assignment #3 - pandas (20 points)

## Due: 2/5 (10 pm)

## Worked in Group with Kunal(Mahes1k), Anurag(Ambek1a), Pramod(Anant1p)

This assignment is designed to give you some hands-on practice with pandas.

For the first problem, as you are being asked to write a function, you must include code within the function to check for valid input parameter values as well as code that calls the function for multipe test cases with valid and invalid actual parameter values.

**Make sure to add a Markdown cell after your code for each problem that explains your test cases and results**.

For this assignment, you were given a group number during class.   There are lettered problems A - R on the other attached handout to this assignment.   For problems #2-#4, you need only to complete the three specific lettered problems associated with the group number you were assigned.

## Problem 1 (11 pts.) - Do the following in the code cell below:

### Write a Python function that has as input a Python dictionary and a numPy array of strings.  The function should validate that all values in the dictionary are Python lists of equal length and that the length of the numPy array is also the same as the length of the dictionary list values.   Using the dictionary and list, the function should create and return a pandas dataframe.

Sample Python dictionary data and list labels:

exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],

'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],

'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],

'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}

labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

Expected Output:

attempts name qualify score

a 1 Anastasia yes 12.5

b 3 Dima no 9.0

.... i 2 Kevin no 8.0

j 1 Jonas yes 19.0

## The function genDataFrame(dict,ndarray) will take two parameters, a python dictionary and an numpy array. The python dict will be used as the data for the pandas dataframe and the numpy array will be used as the index labels for the dataframe.

**The function will check the inputs if they are of type dictionary and an numpy array, and if that is correct, it will check if the size of all the values and the numpy array used as labels, are of same size alongwith the type of all values present in the dict should be of list**

### Test Cases

**Test#1 : Happy Flow**<br>
The first Test is a Happy flow and accepts a dictionary and a numpy array of label values. the return a pandas dataframe after it passes all the validity checks

**Test#2 : When the size of labels is not equal to**<br>
The Test case takes a valid dictionary and valid numpy array as parameter but the length of the array is not equal to the size of the values. This fails with the validity checks and returns message **There is an error in the lengths of the data**

**Test#3 : When the length of one of the key:value in dict is not equal**<br>
The Test case takes a dictionary and a valid numpy array as parameter but the length of one of the values in the dictionary is not equal to other values or simply put, all the values in the dictionary are of same length. This will fail with teh validity checks and returns message **There is an error in the lengths of the data**

**Test#4 : When not all the values in the dict are of list type**<br>
The Test takes a dictionary and an numpy array, the dictionary does not have all the values of type list, which will fail at the validity checked for the type of all the values inside of dictionary to be list. The function will return **When not all the values in the dict are of list type**

**Test#5 : When the first parameter is not of type dictionary**<br>
The Test takes a non dictionary input as a first parameter and an numpy array. The function requires a dictionary to create a pandas dataframe and as the parameter is not of type dictionary, this will fail for the validity checks and returns **The first parameter should be of type dict**

**Test#6 : When the second parameter is not of type numpy array**<br>
The Test takes a dictionary and a non numpy array as second parameter. As the labels are to be in a format of numpy array, this will fail at the validity checks and the function return **When the second parameter is not of type nimpy array**

In [41]:
import pandas as pd
import numpy as np

# exam_data

def genDataFrame(dic,narr):

    # print(type(narr))

    if(type(dic)!=dict):
        return "The first parameter should be of type dict"
    if(type(narr)!=np.ndarray):
        return "The second parameter should be of type list to be used as labels"

    # errMsg
    lengths = [len(val) for val in dic.values()]
    lengths.append(len(narr))
    lengths = set(lengths)

    types = [type(val) for val in dic.values()]
    types = set(types)
    

    # print(types)
    if(len(types) != 1 or types.pop() != list):
        return "The data in dictonary is not of valid types"
    if(len(lengths) == 1):
        df = pd.DataFrame(data = dic, index=narr)
        return df
    return "There is an error in the lengths of the data"

# print(genDataFrame(exam_data,labels))

In [42]:
#Test 1
exam_data = {
    'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
    'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
    'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
    'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}

labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
print('Test#1 : Happy Case')
print(f'Result for Test#1 :\n {genDataFrame(exam_data,np.array(labels))} \n')

#Test 2
exam_data = {
    'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
    'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
    'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
    'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}

labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i']
print('Test#2 : When the size of labels is not equal to')
print(f'Result for Test#2 : {genDataFrame(exam_data,np.array(labels))} \n')

#Test 3
exam_data = {
    'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
    'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
    'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
    'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes'],
    'Test': [1,2,3]}

labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
print('Test#3 : When the length of one of the key:value in dict is not equal')
print(f'Result for Test#3 : {genDataFrame(exam_data,np.array(labels))} \n')

#Test 4
exam_data = {
    'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
    'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
    'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
    'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes'],
    'testkey': 'testvalue'}

labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
print('Test#4 : When not all the values in the dict are of list type')
print(f'Result for Test#4 : {genDataFrame(exam_data,np.array(labels))} \n')

#Test 5
exam_data = ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas']

labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
print('Test#5 : When the first parameter is not of type dictionary')
print(f'Result for Test#5 : {genDataFrame(exam_data,np.array(labels))} \n')

#Test 6
exam_data = {
    'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
    'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
    'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
    'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}

labels = 'Test Label'
print('Test#6 : When the second parameter is not of type nimpy array')
print(f'Result for Test#6 : {genDataFrame(exam_data,labels)} \n')

Test#1 : Happy Case
Result for Test#1 :
         name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes
d      James    NaN         3      no
e      Emily    9.0         2      no
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura    NaN         1      no
i      Kevin    8.0         2      no
j      Jonas   19.0         1     yes

Test#2 : When the size of labels is not equal to
Result for Test#2 : There is an error in the lengths of the data

Test#3 : When the length of one of the key:value in dict is not equal
Result for Test#3 : There is an error in the lengths of the data

Test#4 : When not all the values in the dict are of list type
Result for Test#4 : The data in dictonary is not of valid types

Test#5 : When the first parameter is not of type dictionary
Result for Test#5 : The first parameter should be of type dict

Test#6 : When the second parameter is not of type nimpy array
Result for Test#6 : The second parameter should be of type list to be used as labels

### Problems 2-4 (9 pts.  -  3 pts. each)

### Do the following in the code cell below:

### Complete the problem on the attached pdf file that corresponds to the letter on your paper.

### Group 1 - A, G, M
### Group 2 - B, H, N
### Group 3 - C, I, O
### Group 4 - D, J, P
### Group 5 - E, K, Q
### Group 6 - F, L, R
### Group 7 - A, I, N
### Group 8 - B, J, Q
### Group 9 - C, K, P
### Group 10 - D, L, R

In [43]:
#Utility function to get a pandas dataframe 


def getSampleDF():
    di = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
    'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
    'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
    'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
    la = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i','j']
    return pd.DataFrame(data = di,index=la)

# Group 2 : B,H,N

### B: 
Write a Pandas program to select the 'name' and 'score' columns from the following DataFrame.<br>
Sample Python dictionary data and list labels:<br>
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],

'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],

'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],

'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}

labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

Expected Output:

Select specific columns:

name score

a Anastasia 12.5

b Dima 9.0

c Katherine 16.5

... 

h Laura NaN

i Kevin 8.0

j Jonas 19.0

**The Below line of code will only retreive the columns 'name' and 'score' from the dataframe using a filter**

In [44]:
df = getSampleDF()

print(df.filter(items = ['name','score'],axis=1))

        name  score
a  Anastasia   12.5
b       Dima    9.0
c  Katherine   16.5
d      James    NaN
e      Emily    9.0
f    Michael   20.0
g    Matthew   14.5
h      Laura    NaN
i      Kevin    8.0
j      Jonas   19.0

### H: 
Write a Pandas program to select the rows where number of attempts in the examination is less than 2 and score greater than 15.<br>
Sample Python dictionary data and list labels:<br>
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],

'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],

'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],

'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}

labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

Expected Output:

Number of attempts in the examination is less than 2 and score greater than 15 :

name score attempts qualify

j Jonas 19.0 1 yes

**To retreive the data where the values of attempts are less then 2 and the score is above 15. we can use either directly applying logical statements (which are commented out for the output) or we can use 'query' which performs similar operation as to pass the logical expression and the function performs a query on the dataframe and returns the values**

In [45]:
df = getSampleDF()

# print(df[(df['attempts']<2) & (df['score']>15)])
print(df.query('attempts < 2 and score > 15'))

    name  score  attempts qualify
j  Jonas   19.0         1     yes

### N. 
Write a Pandas program to replace the 'qualify' column contains the values 'yes' and 'no' with True and False.<br>
Sample Python dictionary data and list labels:<br>
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],

'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],

'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],

'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}

labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

Expected Output:

Replace the 'qualify' column contains the values 'yes' and 'no' with
True and False:

attempts name qualify score

a 1 Anastasia True 12.5

b 3 Dima False 9.0

......

i 2 Kevin False 8.0

j 1 Jonas True 19.0

**To get the desired output, we can directly update the data into the dataframe by applying a condition which will return a desired value of 'True' or 'False' which can then be then printed as wanted. To update the column 'qualify', we can use the numpy where function which will apply the logical if else condition and update the values to 'True' if 'qualify' ='yes' otherwise to 'False'**

In [46]:
df = getSampleDF()

df['qualify'] = np.where(df['qualify']=='yes',True,False)
df

        name  score  attempts  qualify
a  Anastasia   12.5         1     True
b       Dima    9.0         3    False
c  Katherine   16.5         2     True
d      James    NaN         3    False
e      Emily    9.0         2    False
f    Michael   20.0         3     True
g    Matthew   14.5         1     True
h      Laura    NaN         1    False
i      Kevin    8.0         2    False
j      Jonas   19.0         1     True